
DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(255) DEFAULT NULL,
  CONTRASENA varchar(255) DEFAULT NULL,
  TELEFONO varchar(10) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  EDAD int(10) DEFAULT NULL,
  SALDO float(100) DEFAULT NULL,
  LOCALES_PREFERIDOS float(100) DEFAULT NULL,
  RESERVAS float(100) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ;

--
-- Dumping data for table `user_details`
--